### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by JVSeidel** [Hoeijmakers/getbib#1]
I have a puzzle for you! 

I queried a paper like so:
 _python3 getbib.py Bonfils 2012 2012_

Got this:

_0)    11/2012    Bonfils, X et al.
       Metallicity
1)    11/2012    Bonfils, X.; Gillon, M.; Udry, S et al.
       VizieR Online Data Catalog: Radial velocity and photometry for GJ3470 (Bonfils+, 2012)
2)    10/2012    Bonfils, X.; Gillon, M.; Udry, S et al.
       A hot Uranus transiting the nearby M dwarf GJ 3470. Detected with HARPS velocimetry. Captured in transit with TRAPPIST photometry_

Selected this:

_Which reference do you want? q for cancel.
Separate more than one number with a comma.
2_

And got this error: 

_Error: The reference you are trying to add is not an ARTICLE,
INPROCEEDINGS OR MISC. Sorry, you need to add it manually._

But when I check manually, it is in fact, an ARTICLE. Any ideas? This has happened for a bunch of papers, all older than 2012ish.

**Comment by Hoeijmakers** [comment]
Hi Julia,

Thanks for testing my code with live fire.

Unfortunately I cannot reproduce this error. Did you upgrade to the latest
version?

Jens

**Comment by JVSeidel** [comment]
Hi Jens,

updated my fork, worked like a charm. Thanks!

Just one thing. When you have someone with a lot of budget (and thus a lot of conference proceedings) it's not that easy to see which one is the article and which one a proceeding with the same name or similar. Is there a possibility to display what type of entry it is?

**Comment by Hoeijmakers** [comment]
Checking that it is an INPROCEEDINGS is difficult because it requires access to the bibtex script itself, which I don't query unless the user asks for it. Instead, I have now made it print the bibliographic reference to screen, from which you can see whether it is a journal or something else (like you would in ADS). Update your fork again.

**Comment by Hoeijmakers** [comment]
And don't forget to add it to your path! It's such a breeze.....
